# Blocos que quebram com 1 hit e já dropam em modo Adventure.
easy-dropped-itens:
  - TALL_GRASS
  - SHORT_GRASS
  - FERN
  - LARGE_FERN
  - DANDELION
  - POPPY
  - BLUE_ORCHID
  - OXEYE_DAISY
  - SUGAR_CANE
  - BAMBOO
  - KELP_PLANT
  - KELP
  - SWEET_BERRY_BUSH

# Blocos onde blocos colocáveis podem ser colocados (CanPlaceOn).
canplaceon-itens:
  - GRASS_BLOCK
  - SAND
