# Blocos que quebram com 1 hit e já dropam em modo Adventure.
easy-dropped-itens:
  - TALL_GRASS
  - SHORT_GRASS
  - FERN
  - LARGE_FERN
  - DANDELION
  - POPPY

# Blocos onde blocos colocáveis podem ser colocados (CanPlaceOn).
canplaceon-itens:
  - GRASS_BLOCK
  - SAND
